image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
configuration:
  - Debug
services:
  - postgresql94
init:  
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
before_build:
  - cmd: nuget install NUnit.Console -Version 3.7.0 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install codecov
build:
  project: Redshift.sln
  publish_nuget: true
  include_nuget_references: true
before_test:  
    - psql -c "CREATE DATABASE redshifttest;" -U postgres
    - psql -c "CREATE USER redshifttest WITH PASSWORD '1234';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE redshifttest TO redshifttest;"
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion
after_test:
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\Redshift.Orm.Tests\Redshift.Orm.Tests.csproj" -filter:"+[Redshift.Orm*]* -[Redshift.Orm.Tests*]*" -output:"coverage.xml"
  - codecov -f "coverage.xml" -t 6c8ebd66-9dd1-42b7-b2ba-7f23f68a0ec2
deploy:
  provider: NuGet
  name: production
  on:
    branch: master
  api_key:
    secure: ouyNmR9mcTyxD7Ie8GEeyXFkYNIYRkkTpACNKgqFr8Z1xlKgfPO819gj4mucy+bh
  skip_symbols: false
  artifact: /.*\.nupkg/